version: '3.8'

services:
  knowledgebeast:
    build: .
    image: knowledgebeast:latest
    container_name: knowledgebeast
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - KB_DATA_DIR=/app/data
      - KB_LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: knowledgebeast-network
