# Grafana datasource configuration for Prometheus
# Documentation: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources

apiVersion: 1

# List of datasources to insert/update depending on what's available in the database
datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      # HTTP method (POST is recommended for long queries)
      httpMethod: POST

      # Timeout for queries
      timeInterval: 15s

      # Query timeout
      queryTimeout: 60s

      # Custom query parameters
      customQueryParameters: ''

      # Disable metrics lookup (faster dashboard loading)
      disableMetricsLookup: false

      # Increment query (auto-adjust time range)
      incrementalQuerying: false

      # Prometheus type (prometheus or cortex)
      prometheusType: Prometheus

      # Prometheus version
      prometheusVersion: 2.47.0

      # Cache level
      cacheLevel: Low

      # Exemplars enabled
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger

    # Version (increment to force reload)
    version: 1

    # Org ID
    orgId: 1

    # UID (unique identifier)
    uid: prometheus

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      # Trace to logs integration
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false

      # Node graph
      nodeGraph:
        enabled: true

    version: 1
    orgId: 1
    uid: jaeger

  # Loki datasource for logs (optional - uncomment if Loki is deployed)
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   url: http://loki:3100
  #   isDefault: false
  #   editable: true
  #   jsonData:
  #     maxLines: 1000
  #     derivedFields:
  #       - datasourceUid: jaeger
  #         matcherRegex: "traceID=(\\w+)"
  #         name: TraceID
  #         url: '$${__value.raw}'
  #   version: 1
  #   orgId: 1
  #   uid: loki
